# Generated by Django 3.0.2 on 2020-01-02 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.CharField(max_length=20, verbose_name='Allocation')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('percentage', models.IntegerField(verbose_name='Percentage')),
                ('unit_value', models.IntegerField(verbose_name='Value')),
                ('initial', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to='historical_performance.Initial', verbose_name='Portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='PerformancePortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('unit_value', models.IntegerField(verbose_name='Value')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performances', to='historical_performance.Portfolio', verbose_name='Portfolio')),
            ],
        ),
    ]
