# Generated by Django 3.0.2 on 2020-01-03 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('historical_performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(max_length=20, verbose_name='Stock')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentage')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Value')),
            ],
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='allocation',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='initial',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='unit_value',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='initial_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Initial Balance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='residual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Residual value'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='username',
            field=models.CharField(default='default', max_length=255, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Initial',
        ),
        migrations.AddField(
            model_name='allocation',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to='historical_performance.Portfolio', verbose_name='Portfolio'),
        ),
    ]
