# Generated by Django 3.0.2 on 2020-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historical_performance', '0003_auto_20200104_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='percentage',
            field=models.PositiveIntegerField(verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='performanceportfolio',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Value'),
        ),
    ]
