# Generated by Django 3.0.2 on 2020-01-18 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('historical_performance', '0004_auto_20200104_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceportfolio',
            name='percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Percentage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='performanceportfolio',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='performanceportfolio',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='historical_performance.Allocation', verbose_name='Portfolio'),
        ),
    ]
